import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  // const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  PhoneNumberView: {
    flexDirection: 'row',
    borderRadius: 5,
    width: 350,
    height: 50,
    borderColor: '#fff',
    opacity: 35,
    borderWidth: 0,
    // justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
    color: '#FFFFFF',
    fontSize: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  containerImage: {
    flex: 1,
    flexDirection: 'column',
  },
  skip: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    marginRight: 20,
    textAlign: 'right',
    fontFamily: 'Helvetica Neue',
    fontSize: 18,
    color: '#FFFFFF',
  },
  logo: {
    height: 60,
    resizeMode: 'contain',
    width: 45,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  leftContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: 10,
  },
  rightContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  TopContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    //justifyContent: 'flex-start',
    position: 'absolute',
    //alignContent: 'flex-start',
    top: 40,
  },
  EnterMessage: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    fontFamily: 'Proxima Nova',
    fontSize: 18,
    color: '#FFFFFF',
    marginBottom: 10,
    marginTop: 10,
  },
  Login: {
    fontSize: 21,
    fontFamily: 'Proxima Nova',
    color: '#FFFFFF',
    marginTop: 10,
    marginBottom: 10,
  },
  PhoneNumber: {
    flexDirection: 'row',
    borderRadius: 5,
    width: 250,
    height: 50,
    borderColor: '#fff',
    opacity: 35,
    marginLeft: 10,
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
    color: '#FFFFFF',
    fontSize: 17,
  },
  // PhoneNumber: {
  //   flexDirection: 'row',
  //   borderRadius: 5,
  //   width: 350,
  //   height: 50,
  //   borderColor: '#FFFFFF',
  //   opacity: 35,
  //   borderWidth: 1,
  //   borderRadius: 5,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   marginBottom: 10,
  //   marginTop: 10,
  //   color: '#FFFFFF',
  //   fontSize: 14,
  // },
  PhoneContainer: {
    flexDirection: 'row',
    borderRadius: 5,
    width: 350,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
    color: '#FFFFFF',
    backgroundColor: 'transparent'
  },
  signIn: {
    fontSize: 18,
    fontFamily: 'Helvetica Neue',
    color: '#FFFFFF',
    justifyContent: 'center',
    textAlign: 'center',
  },
  bottomBox: {
    flex: 1,
    width: '100%',
    height: 350,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
    backgroundColor: 'transparent',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  ImageIconStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
  },
  buttonHeading: {
    marginTop: 10,
    marginBottom: 10,
    fontSize: 21,
    fontWeight: 'bold',
    color: '#fff',
  },
  buttonSubHeading: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  page: {
    flex: 1,
    //alignItems: 'center',
    //justifyContent: 'center',
  },
  textInput: {
    marginTop: 20,
    width: '90%',
    height: 40,
    borderColor: '#555',
    borderWidth: 2,
    borderRadius: 5,
    paddingLeft: 10,
    color: '#fff',
    fontSize: 18,
  },
  themeButton: {
    width: '90%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#888',
    borderColor: '#555',
    borderWidth: 2,
    borderRadius: 5,
  },
  themeButtonTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  verificationView: {
    width: '100%',
    alignItems: 'center',
    marginTop: 50,
  },
  gradBtn: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  }
});