export const gif = {
    'Champagne': require('../../../assets/newgif/Champagne.webp'),
    'Cherry': require('../../../assets/newgif/Cherrys-2.webp'),
    'DiamondEarrings': require('../../../assets/gif/gif/DiamondEarrings.webp'),
    'Dress': require('../../../assets/gif/gif/Dress.webp'),
    'DiamondNeckless': require('../../../assets/gif_new/DiamondNeckless.webp'),
    'DiamondRing': require('../../../assets/gif/gif/DiamondRing.webp'),
    'Dolphin': require('../../../assets/gif/gif/Dolphin.webp'),
    'GoldEarrings': require('../../../assets/gif/gif/GoldEarrings.webp'),
    'Eyeliner': require('../../../assets/newgif/Eyeliner.webp'),
    'GoldNeckless': require('../../../assets/GoldNeckless.png'),
    'handBag': require('../../../assets/gif/gif/handBag.webp'),
    'Horse': require('../../../assets/newgif/Horse.webp'),
    'Key': require('../../../assets/gif/gif/Key.webp'),
    'Lipstick': require('../../../assets/newgif/Lipstick.webp'),
    'Mango': require('../../../assets/newgif/Mango.webp'),
    'Peach': require('../../../assets/newgif/Peach.webp'),
    'PearlEarrings': require('../../../assets/gif/gif/PearlEarrings.webp'),
    'PearlRing': require('../../../assets/gif/gif/PearlRing.webp'),
    'Perfume': require('../../../assets/gif/gif/Perfume.webp'),
    'Rose': require('../../../assets/newgif/Rose.webp'),
    'RoyalChariot': require('../../../assets/gif/gif/RoyalChariot.webp'),
    'Royalcar': require('../../../assets/gif/gif/Royalcar.webp'),
    'SpeedBoat': require('../../../assets/gif/gif/SpeedBoat.webp'),
    'Sportscar': require('../../../assets/gif/gif/Sportscar.webp'),
    'Watch': require('../../../assets/newgif/Watch.webp'),
    'Wine': require('../../../assets/gif/gif/Wine.webp'),
};