import { StyleSheet, Dimensions, Platform } from 'react-native';
const styles = StyleSheet.create({
  cardContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  rowData: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    borderBottomColor: '#000',
    alignItems: 'center',
    borderBottomWidth: 1,
    height: 70,
    overflow: 'hidden',
    marginBottom: 0,
    marginTop: 1,
    backgroundColor: '#111'
    // borderRadius: 40,
  },
  editIcon: {
    justifyContent: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    width: 30,
    height: 30,
  },
  leftContainer: {
    //width: Dimensions.get('screen').width / 1.2,
    flex: 10,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginLeft: 40,
  },
  rightContainer: {
    justifyContent: 'flex-start',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
  },
  menuList: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginTop: 30,
    flex: 1,
  },
  userProfile: {
    flexDirection: 'row',
  },
  menuItem: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 10,
    marginLeft: 10,
    //width: Dimensions.get('screen').width / 2,
  },
  icon: {
    width: 45,
    height: 45,
    marginLeft: 10,
    borderRadius: 40,
    overflow: 'hidden',
  },
  headerContainer: {
    alignItems: 'center',
    backgroundColor: '#000000',
    marginBottom: 10,
    marginTop: 10,
  },
  indicatorTab: {
    backgroundColor: 'transparent',
  },
  scroll: {
    flex: 1,
    backgroundColor: '#000000',
  },
  sceneContainer: {
    marginTop: 10,
  },
  socialIcon: {
    marginLeft: 14,
    marginRight: 14,
  },
  socialRow: {
    flexDirection: 'row',
  },
  tabBar: {
    backgroundColor: '#000000',
  },
  tabContainer: {
    flex: 1,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#ffffff',
    borderBottomWidth: 0.2,
    borderTopColor: '#ffffff',
    borderTopWidth: 0.2,
  },
  tabLabel: {
    fontSize: 18,
    textAlign: 'center',
    color: '#ffffff',
    marginBottom: 10,
    paddingTop: 10,
  },
  tabLabelNumber: {
    //color: 'gray',
    fontSize: 18,
    textAlign: 'center',
    color: 'gold',
    paddingBottom: 10,
  },
  menuText: {
    fontSize: 18,
    fontWeight: '400',
    //textAlign: 'left',
    marginLeft: 25,
    alignItems: 'flex-start',
    flex: 3,
    color: '#ffffff',
  },
  rightText: {
    flex: 1,
    color: '#ffffff',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    paddingVertical: 2,
  },
  list: {
    flex: 1,
    borderRadius: 40,
    borderColor: '#ffffff',
    borderWidth: 2,
    alignContent: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
    //margin: 5,
    // height: 40,
  },
  tabLabelText: {
    color: 'black',
    fontSize: 22.5,
    fontWeight: '600',
    textAlign: 'center',
  },
  userBioRow: {
    marginLeft: 40,
    marginRight: 40,
  },
  userBioText: {
    color: 'gray',
    fontSize: 13.5,
    textAlign: 'center',
  },
  userImage: {
    borderRadius: 60,
    height: 120,
    marginBottom: 10,
    width: 120,
  },
  userNameRow: {
    marginBottom: 10,
  },
  userNameText: {
    color: '#5B5A5A',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  userRow: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    marginBottom: 12,
  },
});
export default styles;
