import { relativeTimeRounding } from 'moment';
import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  skip: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    marginRight: 20,
    textAlign: 'right',
    fontFamily: 'Helvetica Neue',
    fontSize: 18,
    color: '#FFFFFF',
  },
  logo: {
    height: 60,
    resizeMode: 'contain',
    width: 45,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  leftContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: 10,
  },
  rightContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  TopContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    //justifyContent: 'flex-start',
    position: 'absolute',
    //alignContent: 'flex-start',
    top: 40,
  },
  buttonImageIconStyle: {
    padding: 10,
    marginLeft: 30,
    marginRight: 30,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
  },
  signIn: {
    fontSize: 18,
    fontFamily: 'Helvetica Neue',
    color: '#FFFFFF',
    justifyContent: 'center',
    textAlign: 'center',
  },
  signInGoogle: {
    fontSize: 18,
    fontFamily: 'Helvetica Neue',
    color: '#000000',
  },
  PhoneContainer: {
    flexDirection: 'row',
    borderRadius: 5,
    width: 300,
    height: 50,
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  FaceBookContainer: {
    flexDirection: 'row',
    backgroundColor: '#4F70C1',
    borderColor: '#4b91e0',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    height: 50,
    //justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  GoogleContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderColor: '#4b91e0',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    height: 50,
    //justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  signInButton: {
    width: 300,
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    margin: 10,
  },
  containerImage: {
    flex: 1,
    flexDirection: 'column',
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  inputBox: {
    width: '85%',
    margin: 10,
    padding: 15,
    fontSize: 18,
    borderColor: '#d3d3d3',
    borderBottomWidth: 1,
    textAlign: 'center',
  },
  button: {
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 5,
    alignItems: 'center',
    backgroundColor: '#F6820D',
    borderColor: '#F6820D',
    borderWidth: 1,
    borderRadius: 5,
    width: 350,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  Heading: {
    marginBottom: 10,
    fontSize: 21,
    fontWeight: 'bold',
    fontFamily: 'Helvetica Neue',
    color: '#fff',
  },
  SubHeading: {
    marginBottom: 30,
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Helvetica Neue',
    color: '#fff',
    marginBottom: 5,
  },
  buttonTextWhite: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#504f4f',
  },
  buttonSignup: {
    fontSize: 12,
  },
  bottomBox: {
    flex: 1,
    width: '100%',
    height: 300,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
    backgroundColor: 'transparent',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 20,
    alignItems: 'center',
    //height: '30%',
    justifyContent: 'center',
  },
  facebookButton: {
    backgroundColor: '#577fc1',
    borderColor: '#4b91e0',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonMobile: {
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 5,
    alignItems: 'center',
    backgroundColor: '#f1db5c',
    borderColor: '#F6820D',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
  },
});
export default styles;
