const DATA = [
  {
    id: 1,
    title: 'Home',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 2,
    title: 'Moments',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 3,
    title: 'Wallet',
    image: require('../assets/slider.jpg'),
    count: 10,
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 4,
    title: 'Messages',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 5,
    title: 'Topup Crowns',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 6,
    title: 'Refer Friend',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 7,
    title: 'Support',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 8,
    title: 'Home',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 9,
    title: 'Moments',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 10,
    title: 'Wallet',
    image: require('../assets/slider.jpg'),
    count: 10,
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 11,
    title: 'Messages',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 12,
    title: 'Toprup Crowns',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 13,
    title: 'Refer Friend',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 14,
    title: 'Support',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 15,
    title: 'Home',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 16,
    title: 'Moments',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 17,
    title: 'Wallet',
    image: require('../assets/slider.jpg'),
    count: 10,
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 18,
    title: 'Messages',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 19,
    title: 'Toprup Crowns',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 20,
    title: 'Refer Friend',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
  {
    id: 21,
    title: 'Support',
    image: require('../assets/slider.jpg'),
    follow: 'Follow',
    remove: 'Remove',
  },
];
export default DATA;
