import { StyleSheet, Platform } from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#000',
  },
  TopContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 40,
    // backgroundColor:'red'
    // position: 'absolute',
  },
  enableView: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
    marginBottom: 20,
  },
  locationlogoView: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  leftContainer: {
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: 10,
  },
  rightContainer: {
    // flex: 1,
    // backgroundColor:'green',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skip: {
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginRight: 20,
    textAlign: 'right',
    fontFamily: 'Helvetica Neue',
    fontSize: 18,
    color: '#FFFFFF',
  },
  logo: {
    height: 60,
    resizeMode: 'contain',
    width: 45,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  locationImage: {
    height: 100,
    resizeMode: 'stretch',
    width: 80,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    // backgroundColor:'red'
  },
  noGPS: {
    marginTop: 20,
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
  },
  bottomBox: {
    flex: 1,
    width: '100%',
    height: 300,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
    backgroundColor: 'transparent',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 20,
    alignItems: 'center',
    //height: '30%',
    justifyContent: 'center',
  },
  loactioContainer: {
    flexDirection: 'row',
    borderRadius: 5,
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
    textAlign: 'center',
  },
  enableTxt: {
    fontSize: 18,
    fontFamily: 'Helvetica Neue',
    color: '#000',
    justifyContent: 'center',
    textAlign: 'center',
  },
  buttonImageIconStyle: {
    padding: 10,
    marginLeft: 30,
    marginRight: 30,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
  },
});
export default styles;
