const stories = [
  {
    username: 'Lisa',
    views: 10,
    date: '8',
    profile: require('../../../../assets/girl1.png'),
    stories: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1532579853048-ec5f8f15f88d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        type: 'image',
        duration: 2,
        isReadMore: true,
        text: '',
      },
      {
        id: 2,
        url: 'https://www.youtube.com/watch?v=wWLOhHVPE7Q',
        type: 'video',
        duration: 20,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
        text: '',
      },
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1498982261566-1c28c9cf4c02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
        text: '',
      },
    ],
  },
  // {
  //   username: 'Andrea',
  //   views:3,
  //   date:'8',
  //   profile: require('../../../../assets/girl2.png'),
  //   stories: [
  //     {
  //       id: 1,
  //       url: 'https://images.unsplash.com/photo-1500099817043-86d46000d58f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isReadMore: true,
  //       text:'',
  //     },
  //     {
  //       id: 2,
  //       url: 'https://www.youtube.com/watch?v=wWLOhHVPE7Q',
  //       type: 'video',
  //       duration:20,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //     {
  //       id: 3,
  //       url: 'https://images.unsplash.com/photo-1498982261566-1c28c9cf4c02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //   ],
  // },
  // {
  //   username: 'Sona',
  //   views:9,
  //   date:'8',
  //   profile: require('../../../../assets/girl3.png'),
  //   stories: [
  //     {
  //       id: 1,
  //       url: 'https://images.unsplash.com/photo-1515578706925-0dc1a7bfc8cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isReadMore: true,
  //       text:'',
  //     },
  //     {
  //       id: 2,
  //       url: 'https://images.unsplash.com/photo-1496287437689-3c24997cca99?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //     {
  //       id: 3,
  //       url: 'https://images.unsplash.com/photo-1514870262631-55de0332faf6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //   ],
  // },
  // {
  //   username: 'Linda',
  //   date:'8',
  //   views:4,
  //   profile: require('../../../../assets/girl4.png'),
  //   stories: [
  //     {
  //       id: 3,
  //       src: 'https://images.unsplash.com/photo-1512101176959-c557f3516787?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isReadMore: true,
  //       text:'',
  //     },
  //     {
  //       id: 5,
  //       url: 'https://images.unsplash.com/photo-1478397453044-17bb5f994100?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
  //       type: 'image',
  //       duration: 2,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //     {
  //       id: 4,
  //       url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=581&q=80',
  //       type: 'image',
  //       duration: 2,
  //       isSeen: false,
  //       isReadMore: true,
  //       isPaused: true,
  //       text:'',
  //     },
  //   ],
  // },
  // {
  //   username : 'sonia',
  //   date:'8',
  //   views:2,
  //   profile: require('../../../../assets/girl5.png'),
  //   stories: [],
  // }
];
export default stories;
