import { StyleSheet, Platform, Dimensions } from 'react-native';
const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#000',
  },
  TopContainer: {
    //flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        marginTop: 10,
      },
      android: { marginTop: 10 },
    }),
    //marginTop: 40,
    // backgroundColor:'red'
    // position: 'absolute',
  },
  logo: {
    // height: 30,
    resizeMode: 'contain',
    // width: 30,
    justifyContent: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    marginLeft: 0,
  },
  textFieldInput: {
    // paddingLeft:20,
    // height: 30,
    marginLeft: 10,
    resizeMode: 'contain',
    //width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    tintColor: 'gold',
  },
  textFieldInput1: {
    marginLeft: 10,
  },
  PhoneNumber: {
    height: 50,
    width: deviceWidth - 110,
    color: '#fff',
    marginLeft: 10,
    //   backgroundColor:'red',
    // // flexDirection: 'row',
    // borderRadius: 5,
    // width: 50,
    // height: 50,
    // borderColor: '#fff',
    // opacity: 35,
    // marginLeft: 10,
    // alignItems: 'center',
    // marginBottom: 10,
    // marginTop: 10,
    // color: '#FFFFFF',
    // fontSize: 17,
  },
  genderText: {
    // fontFamily: fonts.PoppinsMedium,
    textAlign: 'center',
    fontSize: 15,
    color: '#fff',
  },
  scrollView: {
    flex: 13,
    backgroundColor: '#000',
  },
  viewStyle: {
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  icon: {
    margin: 10,
    marginRight: 1,
    height: 20,
    width: 20,
    tintColor: 'red',
    resizeMode: 'contain',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  PhoneContainer: {
    //top: 50,
    flexDirection: 'row',
    borderRadius: 5,
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
    textAlign: 'center',
  },
  signIn: {
    fontSize: 18,
    fontFamily: 'Helvetica Neue',
    color: '#000',
    justifyContent: 'center',
    textAlign: 'center',
  },
  iconRight: {
    margin: 10,
    marginRight: 10,
    height: 20,
    width: 20,
    tintColor: 'gold',
    resizeMode: 'contain',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  pickerView: {
    alignItems: 'center',
    height: 50,
    borderWidth: 1,
    width: '100%',
    marginTop: 20,
    backgroundColor: '#222',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingRight: 20,
    // paddingHorizontal:20
  },
  textFiledView: {
    height: 50,
    borderWidth: 1,
    width: '100%',
    marginTop: 20,
    backgroundColor: '#222',
  },
  viewStyles: {
    width: 50,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
  },
  rightContainer: {
    // flex: 1,
    // backgroundColor:'green',
    marginRight: 20,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  marker: {
    height: 30,
    resizeMode: 'contain',
    width: 30,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  leftContainer: {
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginLeft: 10,
  },
  skip: {
    // flex: 1,
    // backgroundColor:'red',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginLeft: 0,
    textAlign: 'right',
    // fontFamily: 'Helvetica Neue',
    fontSize: 18,
    color: '#FFFFFF',
  },
  genderTextView: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 20,
  },
  genderView: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 20,
  },
  genderImageView: {
    width: '33%',
    height: 100,
    flexDirection: 'column',
    alignItems: 'center',
  },
  unselectedGender: {
    width: 60,
    height: 60,
    // tintColor: '#ccc',
    //tintColor: '#cccc',
  },
  selectedGender: {
    width: 80,
    height: 80,
    // tintColor: '#fff',
  },
  notification: {
    height: 60,
    resizeMode: 'contain',
    width: 60,
    marginLeft: 20,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
});
export default styles;
